export const CURRENT_CIRCUIT_ASSET_MAP: Record<
  string,
  { openF1CircuitName?: string }
> = {
  albert_park: { openF1CircuitName: "Melbourne" },
  americas: { openF1CircuitName: "Austin" },
  bahrain: { openF1CircuitName: "Sakhir" },
  baku: { openF1CircuitName: "Baku" },
  catalunya: { openF1CircuitName: "Catalunya" },
  hungaroring: { openF1CircuitName: "Hungaroring" },
  imola: { openF1CircuitName: "Imola" },
  interlagos: { openF1CircuitName: "Interlagos" },
  istanbul: {},
  jeddah: { openF1CircuitName: "Jeddah" },
  las_vegas: { openF1CircuitName: "Las Vegas" },
  vegas: { openF1CircuitName: "Las Vegas" },
  losail: { openF1CircuitName: "Lusail" },
  lusail: { openF1CircuitName: "Lusail" },
  madring: { openF1CircuitName: "Madring" },
  marina_bay: { openF1CircuitName: "Singapore" },
  miami: { openF1CircuitName: "Miami" },
  monaco: { openF1CircuitName: "Monaco" },
  monza: { openF1CircuitName: "Monza" },
  portimao: {},
  red_bull_ring: { openF1CircuitName: "Spielberg" },
  ricard: {},
  rodriguez: { openF1CircuitName: "Mexico City" },
  shanghai: { openF1CircuitName: "Shanghai" },
  silverstone: { openF1CircuitName: "Silverstone" },
  sochi: {},
  spa: { openF1CircuitName: "Spa-Francorchamps" },
  suzuka: { openF1CircuitName: "Suzuka" },
  villeneuve: { openF1CircuitName: "Montreal" },
  yas_marina: { openF1CircuitName: "Yas Marina" },
  zandvoort: { openF1CircuitName: "Zandvoort" },
};
