/** Short friendly display name for each circuit (shown in dropdown and headers). */
export const CIRCUIT_DISPLAY_NAMES: Record<string, string> = {
  albert_park: "Australian GP",
  americas: "US GP",
  bahrain: "Bahrain GP",
  baku: "Azerbaijan GP",
  catalunya: "Spanish GP",
  hungaroring: "Hungarian GP",
  imola: "Emilia Romagna GP",
  interlagos: "Brazilian GP",
  jeddah: "Saudi Arabian GP",
  las_vegas: "Las Vegas GP",
  losail: "Qatar GP",
  marina_bay: "Singapore GP",
  miami: "Miami GP",
  monaco: "Monaco GP",
  monza: "Italian GP",
  red_bull_ring: "Austrian GP",
  rodriguez: "Mexican GP",
  shanghai: "Chinese GP",
  silverstone: "British GP",
  spa: "Belgian GP",
  suzuka: "Japanese GP",
  villeneuve: "Canadian GP",
  yas_marina: "Abu Dhabi GP",
  zandvoort: "Dutch GP",
};

/** Extra search keywords (city names, nicknames) so users can find circuits easily. */
export const CIRCUIT_ALIASES: Record<string, string> = {
  albert_park: "Melbourne Australian GP",
  americas: "Austin COTA US GP American United States",
  bahrain: "Sakhir Bahrain GP",
  baku: "Baku Azerbaijan GP Street",
  catalunya: "Barcelona Spanish GP Spain",
  hungaroring: "Budapest Hungarian GP Hungary",
  imola: "Imola Emilia Romagna GP",
  interlagos: "Interlagos Sao Paulo Brazilian GP Brazil",
  jeddah: "Jeddah Saudi Arabian GP",
  las_vegas: "Las Vegas Strip GP Nevada",
  losail: "Losail Qatar GP Doha",
  marina_bay: "Marina Bay Singapore GP Night",
  miami: "Miami GP Florida",
  monaco: "Monaco Monte Carlo GP",
  monza: "Monza Italian GP Italy Temple of Speed",
  red_bull_ring: "Spielberg Austrian GP Austria Red Bull Ring",
  rodriguez: "Mexico City Mexican GP",
  shanghai: "Shanghai Chinese GP China",
  silverstone: "Silverstone British GP England UK",
  spa: "Spa Francorchamps Belgian GP Belgium",
  suzuka: "Suzuka Japanese GP Japan",
  villeneuve: "Montreal Canadian GP Canada Gilles Villeneuve",
  yas_marina: "Yas Marina Abu Dhabi GP",
  zandvoort: "Zandvoort Dutch GP Netherlands",
};
